services:
  - type: web
    name: employee-salary-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=10000
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
